################################################################################
#
#   Hyprland conf by Gabriel Grechuk
#
#   Window specific rules.
#
#   The tansparent alacritty config.
#
################################################################################

windowrule {
  name = terminal-opacity
  match:class = Alacritty

  opacity = 0.95 0.85
}
